import 'package:Travelon/features/trip/domain/entities/assigned_employee.dart';
import 'package:Travelon/features/trip/domain/entities/current_trip.dart';
import 'package:Travelon/features/trip/domain/entities/trip.dart';
import 'package:Travelon/features/trip/domain/entities/trip_with_places.dart';

/// ---------------------------------------------------------------------------
/// TripRepository
/// ---------------------------------------------------------------------------
/// Abstract contract for Trip-related data operations.
/// 
/// This interface defines the API for managing the entire trip lifecycle,
/// including discovery, booking, active tracking, and post-trip feedback.
/// ---------------------------------------------------------------------------
abstract class TripRepository {

  /// -------------------------------------------------------------------------
  /// Retrieves the trip the user is currently participating in.
  /// -------------------------------------------------------------------------
  Future<CurrentTrip?> getCurrentTrip();

  /// -------------------------------------------------------------------------
  /// Fetches all points of interest/places managed by a specific agency.
  /// -------------------------------------------------------------------------
  Future<List<dynamic>> getAgencyPlaces(String agencyId);

  /// -------------------------------------------------------------------------
  /// Initiates a new trip request with a specific agency for a date range.
  /// 
  /// Returns the unique [requestId] generated by the backend.
  /// -------------------------------------------------------------------------
  Future<String> requestTrip({
    required String touristId,
    required String agencyId,
    required DateTime StartDate,
    required DateTime EndDate,
  });

  /// -------------------------------------------------------------------------
  /// Finalizes the trip itinerary by associating specific places with a request.
  /// -------------------------------------------------------------------------
  Future<void> selectPlaces({
    required String requestId,
    required List<int> placeIds,
  });

  /// -------------------------------------------------------------------------
  /// Submits a numerical rating for an employee after trip completion.
  /// -------------------------------------------------------------------------
  Future<void> rateEmployee({
    required int tripId,
    required int employeeId,
    required int rating,
  });

  /// -------------------------------------------------------------------------
  /// Checks if a rating has already been submitted for a specific trip.
  /// -------------------------------------------------------------------------
  Future<Map<String, dynamic>> getRatingStatus({
    required int tripId,
  });

  /// -------------------------------------------------------------------------
  /// Fetches details of the employee assigned to guide the current trip.
  /// -------------------------------------------------------------------------
  Future<AssignedEmployee?> getAssignedEmployee();

  /// -------------------------------------------------------------------------
  /// Retrieves a summary list of all trips taken by a specific tourist.
  /// -------------------------------------------------------------------------
  Future<List<Trip>> getTouristTrips(String touristId);

  /// -------------------------------------------------------------------------
  /// Retrieves detailed trip records including full itinerary (places) for a tourist.
  /// -------------------------------------------------------------------------
  Future<List<TripWithPlaces>> getTouristTripsPlaces(String touristId);
}